version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: buscar_piso_mysql
    restart: always
    environment:
      MYSQL_DATABASE: buscar_piso_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: piso_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: