services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "${HOST_PORT}:8069"
    environment:
      - HOST=${DB_HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./keys:/etc/odoo/keys
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data: